language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
before_install:
  - wget https://github.com/jedisct1/libsodium/releases/download/0.7.0/libsodium-0.7.0.tar.gz
  - tar xzvf libsodium-0.7.0.tar.gz
  - cd libsodium-0.7.0
  - ./configure && make && make check && sudo make install
  - sudo ldconfig
  - cd ..
install: "pip install -r requirements.txt"
script: nosetests --with-coverage --cover-erase --cover-package=pymacaroons
after_success: coveralls

